// services/readme-generator.service.ts

interface RepoInfo {
  name: string
  description: string
  languages: string[]
  stars: number
  forks: number
  issues: number
  createdAt: string
  updatedAt: string
  url: string
  owner: string
  topics?: string[]
  defaultBranch?: string
}

export class ReadmeGenerator {
  static generate(repoInfo: RepoInfo): string {
    const {
      name,
      description,
      languages,
      stars,
      forks,
      issues,
      createdAt,
      updatedAt,
      url,
      owner,
      topics = [],
      defaultBranch = 'main'
    } = repoInfo

    const primaryLang = languages[0] || 'Software Development'
    const allLangs = languages.join(', ')

    // 徽章
    const badges = [
      `![License](https://img.shields.io/badge/License-MIT-green.svg)`,
      `![Stars](https://img.shields.io/github/stars/${owner}/${name}?style=social)`,
      `![Forks](https://img.shields.io/github/forks/${owner}/${name}?style=social)`,
      `![Issues](https://img.shields.io/github/issues/${owner}/${name})`,
      ...(languages.length > 0 ? [`![Language](https://img.shields.io/github/languages/top/${owner}/${name})`] : [])
    ].join(' ')

    // 语言分布
    const langDistribution = languages.map((lang) => {
      const emoji = ['📘', '📗', '📙', '📕', '📒', '📓'][languages.indexOf(lang) % 6]
      return `- ${emoji} **${lang}**: Core language`
    }).join('\n')

    // 主题标签
    const topicsSection = topics.length > 0 
      ? topics.map(t => `\`${t}\``).join(' ')
      : ''

    return `# ${name}

${badges}

${description || `A professional software project built with ${primaryLang}`}

${topicsSection}

---

## 📖 Table of Contents

- [Overview](#-overview)
- [Features](#-features)
- [Tech Stack](#-tech-stack)
- [Getting Started](#-getting-started)
- [Project Structure](#-project-structure)
- [Contributing](#-contributing)
- [License](#-license)

---

## 📋 Overview

**${name}** is a professional-grade software project built with ${allLangs || primaryLang}.

### 📊 Key Metrics

| Metric | Value |
|--------|-------|
| **Primary Language** | ${primaryLang} |
| **Total Languages** | ${languages.length} |
| **Stars** | ⭐ ${stars} |
| **Forks** | 🍴 ${forks} |
| **Open Issues** | 🐛 ${issues} |
| **Created** | ${createdAt} |
| **Last Updated** | ${updatedAt} |

---

## ✨ Features

${languages.map((lang: string) => `- ✅ **${lang}** core implementation`).join('\n')}
- ✅ Clean, maintainable codebase
- ✅ Version control with Git
${stars > 0 ? `- ✅ ⭐ ${stars} stars from the community` : '- ✅ Ready for community engagement'}

---

## 🛠️ Tech Stack

| Category | Technology |
|----------|------------|
| **Primary Language** | ${primaryLang} |
| **Additional Languages** | ${languages.slice(1).join(', ') || 'N/A'} |
| **Version Control** | Git / GitHub |

### Language Distribution

${langDistribution || '- No language data available'}

---

## 🚀 Getting Started

### Prerequisites

- ${primaryLang} development environment
- Git

### Installation

\`\`\`bash
# Clone the repository
git clone ${url}.git
cd ${name}

# Install dependencies
# (Add specific install commands)

# Run the project
# (Add specific run commands)
\`\`\`

---

## 📁 Project Structure

\`\`\`
${name}/
├── src/                    # Source code
├── tests/                  # Test files
├── docs/                   # Documentation
├── .env.example            # Environment variables template
├── package.json            # Dependencies
└── README.md               # This file
\`\`\`

---

## 🤝 Contributing

1. **Fork** the repository
2. **Clone** your fork
3. **Create** a feature branch
4. **Commit** your changes
5. **Push** to your branch
6. **Open** a Pull Request

### Commit Convention

- \`feat:\` New feature
- \`fix:\` Bug fix
- \`docs:\` Documentation
- \`style:\` Code style
- \`refactor:\` Code refactoring
- \`test:\` Testing
- \`chore:\` Maintenance

---

## 📄 License

This project is licensed under the MIT License.

---

## 📧 Contact

**Maintainer**: [@${owner}](https://github.com/${owner})
**Repository**: [${url}](${url})

---

<div align="center">

### ⭐ If you find this project useful, please consider giving it a star!

*Generated by GitInsight AI*

</div>`
  }
}

// ✅ 默认导出
export default ReadmeGenerator